version: "3.9"
networks:
  bridge_network:
    driver: bridge
services:
  postgresdb:
    container_name: postgres_gbooking_env_local
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=gbookingnkd1996
      - POSTGRES_DB=gbooking
    ports:
      - 5431:5432
    networks:
      - bridge_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: nguyenkimdien02@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Pgadmin3@nguyenkimdon
    ports:
      - 9321:80
    networks:
      - bridge_network
volumes:
  postgres_data:
# docker compose -p env_local_my_gbooking -f docker-compose.env.local.yaml up -d
# docker exec -it postgres_gbooking_env_local /bin/bash
# psql -h localhost -d gbooking -U root
# use gbooking
# docker compose -p env_local_my_gbooking down
# docker run -d -p 9000:9000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
# Portainer admin - lambada246357
