version: "3.9"
networks:
  my_network:
    driver: bridge
services:
  mongo:
    container_name: mongo_pizza_env_local
    image: mongo:6.0
    environment:
      - MONGO_INITDB_DATABASE=pizza
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pizzankd1996
    ports:
      - 24014:27017
    networks:
      - my_network
    volumes:
      - mongo_data:/data/db
      - ./DatabaseBackup:/DatabaseBackup
    restart: unless-stopped
volumes:
  mongo_data:
# docker compose -p env_local_my_pizza -f docker-compose.env.local.yaml up -d
# docker exec -it mongo_pizza_env_local /bin/bash
# docker compose -p env_local_my_pizza down
# docker run -d -p 9000:9000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
# Portainer admin - lambada246357
# mongodump --authenticationDatabase admin --username root --password pizzankd1996 --db pizza --archive > ./DatabaseBackup/pizza-2025-11-17-17h00.tar.gz
# mongorestore --authenticationDatabase admin --username root --password pizzankd1996 --db pizza --archive < ./DatabaseBackup/pizza-2025-04-24-23h30.tar.gz
