version: "3.9"
networks:
  my_network:
    driver: bridge
services:
  mongo:
    container_name: mongo_gbooking_env_staging
    image: mongo:6.0
    environment:
      - MONGO_INITDB_DATABASE=gbooking
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=gbookingnkd1996
    expose:
      - 27017
    networks:
      - my_network
    volumes:
      - mongo_data:/data/db
      - ./DatabaseBackup:/DatabaseBackup
    restart: unless-stopped
  backend:
    container_name: backend_gbooking_env_staging
    build:
      context: ./StackGraphql
      dockerfile: env.staging.Dockerfile
    ports:
      - 8005:8005
    networks:
      - my_network
    restart: unless-stopped
volumes:
  mongo_data:
# docker compose -p env_staging_my_gbooking -f docker-compose.env.staging.yaml up -d
# docker exec -it mongo_gbooking_env_staging /bin/bash
# docker compose -p env_staging_my_gbooking down
# docker run -d -p 9000:9000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
# Portainer admin - lambada246357
# mongodump --authenticationDatabase admin --username root --password gbookingnkd1996 --db gbooking --archive > ./DatabaseBackup/gbooking-2025-04-24-23h30.tar.gz
# mongorestore --authenticationDatabase admin --username root --password gbookingnkd1996 --db gbooking --archive < ./DatabaseBackup/gbooking-2025-04-24-23h45.tar.gz
