import { Footer, Header } from "@/components";
import stylesContainer from "@/scss/container.module.scss";
import "@/scss/app.css";
import { genralSans, kontrap } from "@/utils";
import clsx from "clsx";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import React from "react";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};
type Props = {
  params: Promise<{ locale: string }>;
};
const RootLayout: React.FC<React.PropsWithChildren<Props>> = async ({ children, params }) => {
  const { locale } = await params;
  setRequestLocale(locale);
  const messages = await getMessages();
  return (
    <NextIntlClientProvider locale={locale} messages={messages}>
      <html lang={locale} className={`${genralSans.variable} ${kontrap.variable}`}>
        <body>
          <div className={clsx([stylesContainer.container, "m-auto"])}>
            <Header />
            <main>{children}</main>
            <Footer />
          </div>
        </body>
      </html>
    </NextIntlClientProvider>
  );
};
export default RootLayout;
